use std::{env, fs, path::PathBuf};
use zeroize::Zeroizing;

fn main() {
    embed_private_provider_credentials();
    tauri_build::build();
}

fn embed_private_provider_credentials() {
    println!("cargo:rerun-if-env-changed=TASTELLAR_PROVIDER_CREDENTIALS_FILE");
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let source = env::var_os("TASTELLAR_PROVIDER_CREDENTIALS_FILE")
        .map(PathBuf::from)
        .unwrap_or_else(|| manifest_dir.join("../../../.runtime/provider-credentials.json"));
    println!("cargo:rerun-if-changed={}", source.display());

    let credentials = Zeroizing::new(match fs::read(&source) {
        Ok(contents) => contents,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => b"[]".to_vec(),
        Err(_) => panic!("Could not read private provider configuration"),
    });
    if credentials.len() > 64 * 1024
        || serde_json::from_slice::<Vec<serde_json::Value>>(&credentials).is_err()
    {
        panic!("Private provider configuration must be a JSON array no larger than 64 KB");
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    // This defeats plain-string extraction, not reverse engineering: the app
    // necessarily contains both shares and reconstructs credentials at runtime.
    let mut mask = Zeroizing::new(vec![0u8; credentials.len()]);
    getrandom::fill(&mut mask)
        .unwrap_or_else(|_| panic!("Could not randomize private provider configuration"));
    let payload: Vec<u8> = credentials
        .iter()
        .zip(mask.iter())
        .map(|(a, b)| a ^ b)
        .collect();
    for (name, bytes) in [
        ("provider-data.bin", payload.as_slice()),
        ("provider-mask.bin", mask.as_slice()),
    ] {
        let destination = out_dir.join(name);
        fs::write(&destination, bytes)
            .unwrap_or_else(|_| panic!("Could not prepare private provider configuration"));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&destination, fs::Permissions::from_mode(0o600))
                .unwrap_or_else(|_| panic!("Could not secure private provider configuration"));
        }
    }
    // Remove the plaintext generated by earlier versions in this build directory.
    let legacy = out_dir.join("provider-credentials.json");
    match fs::remove_file(legacy) {
        Ok(()) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(_) => panic!("Could not remove legacy generated provider configuration"),
    }
}
